name: guatentregas
description: Compra a domicilio a los mejores restaurantes en Loja, encuentra cafeterías el delicioso tamal Lojano. Todos los días encontraras restaurant con envío gratis.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.6

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.3
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  device_info: ^2.0.2
  mobile_number: ^1.0.4
  flutter_sim_country_code: ^0.1.1
  receive_sharing_intent: ^1.4.5
  # flutter_paymentez: ^0.0.11 #Descargar binarios https://github.com/paymentez/paymentez-ios, compilar y reemplazar .framework en .symlinks/plugins paymentez ios

  credit_card_validator: ^2.0.0
  google_maps_flutter: ^2.0.6
  location_permissions: ^4.0.0

  permission_asker: ^1.0.0+1
  share: ^2.0.4
  url_launcher: ^6.0.9
  font_awesome_flutter: ^9.1.0

  crypto: ^3.0.1
  universal_platform: ^1.0.0+1
  flutter_local_notifications: ^6.0.0

  location: ^4.3.0
  audioplayers: ^0.19.1

  firebase_core: ^1.10.0
  firebase_auth: ^2.0.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^9.0.0
  firebase_dynamic_links: ^2.0.6

  flutter_sound_lite: ^8.1.9
  socket_io_client: ^1.0.1
  google_sign_in: ^5.0.4
  flutter_login_facebook: ^1.0.1
  the_apple_sign_in: ^1.1.1
  sqflite: ^2.0.0+3
  uuid: ^3.0.4

  image_picker: ^0.8.1+4
  flutter_native_image: ^0.0.6+1
  mime_type: ^1.0.0

  connectivity: ^3.0.6
  modal_progress_hud: ^0.1.3
  animate_do: ^2.0.0

  blinking_point: ^1.0.0+6
  badges: ^2.0.1
  flutter_rating_bar: ^4.0.0
  table_calendar: ^3.0.1
  pin_input_text_field: ^4.1.0
  timer_builder: ^2.0.0
  shimmer_animation: ^2.1.0+1
  month_picker_dialog: ^0.4.0
  percent_indicator: ^3.0.1
  intl_phone_number_input: ^0.7.0+2
  slider_button: ^1.0.0
  flutter_touch_spin: ^2.0.0-nullsafety.1
  flutter_animation_progress_bar: ^2.0.0
  solid_bottom_sheet: ^0.1.10
  flutter_slidable: ^0.6.0
  toggle_switch: ^1.2.0
  qr_flutter: ^4.0.0
  # charts_flutter: ^0.11.0 //Obsoleta en flutter 2.5.0
  like_button: ^2.0.2
  lite_rolling_switch: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/Logo1024.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "assets/icon/Logo1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/screen/
    - assets/pool/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
  androidX: true
